// mand.frag.h
vec3 viridis(float t);
vec3 plasma(float t);
vec3 magma(float t);
vec3 hot(float t);
vec3 coolwarm(float t);
vec3 twilight(float t);
vec3 binary(float t);
vec3 histogramEqualized(float t);
float burningShip();
float tricorn();
float mandOrbitTrap();
float multibrot(double power);
float perpMand();
float celticMand();
float orbitAngle();
float boxTrap();
float ikeda();
float henon();
float lissajous();
float lyapunov();
float collatz();
float biomorph();
float phoenix();
float magnet1();
float nova();
float tetration();
float gingerbreadman();
float duffing();
float tinkerbell();
float gumowski_mira();
float peter_de_jong();
float clifford();
float hopalong();
float apollonian_gasket();
float kleinian();
float fractal_noise();
float worley();